theme: jekyll-theme-minimal
description: PROJECT<a href="https://eikmarizal.github.io/Morse_Code_Translator"> Morse Code Translation</a>
description: Docs<a href="https://eikmarizal.github.io/Machine-Learning-101/"> Machine Learning 101</a>
